language: php

php:
  - 7.1
  - 7.2

matrix:
  include:
  - sudo: true
    dist: trusty
    cache:
      directories: ["$HOME/.composer/cache"]
    before_install:
      - wget https://phar.phpunit.de/phpunit-6.5.13.phar
    script:
      - php phpunit-6.5.13.phar --verbose $PHPUNIT_FLAGS
sudo: false

# cache vendor dirs
cache:
  directories:
  - $HOME/.composer/cache
  - verndor

install:
- travis_retry composer self-update && composer --version
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- travis_retry composer install --prefer-dist --no-interaction

script:
- phpunit --verbose $PHPUNIT_FLAGS
- vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - export CODECOV_TOKEN="3aae9075-186f-444b-bd28-d12e170a24d8"
    - bash <(curl -s https://codecov.io/bash)